services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: fire_qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:

# docker compose up -d to start it, docker compose down to stop it